name = "PowerGrid"
uuid = "41ccd83a-347b-449b-936f-192b657ea7d1"
authors = ["João Rodrigo da Silva Muniz"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
