name = "PowerGrid"
uuid = "41ccd83a-347b-449b-936f-192b657ea7d1"
authors = ["João Rodrigo da Silva Muniz"]
version = "1.0.0-DEV"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2"
PowerModelsDistribution = "0.15"
PythonCall = "0.9"
OrderedCollections = "1"
PowerModels = "0.21"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
